### PR TITLE
ISSUE-140 Redo sample images with inclusion of parallel method

### LINKED ISSUE #140: Sample has missing import
Hello!

Over on:

(Visible on https://microsoft.github.io/just/)

You'll notice that `parallel()` is not imported on that first line.

### PR DESCRIPTION
**Pull request by stanlemon**
Resolves #140

### CODE REVIEW

**Comment by newyork-anthonyng** [comment]
Small nitpick; there's a missing semicolon in the last line.

```diff
- task('say-it-all', parallel('say-hello', 'say-hi'))
+ task('say-it-all', parallel('say-hello', 'say-hi'));
```

**Comment by stanlemon** [comment]
@newyork-anthonyng fixed and updated, thanks!

**Comment by kenotron** [comment]
LGTM as well - I don't have a strong preference on color scheme!

**Comment by stanlemon** [comment]
Whoops, I think I just rolled with the default. I’m happy to change it if anyone has a concern though.

**Comment by kenotron** [comment]
@stanlemon - oh I just realized that you modified the generated docs, not the source `packages/documentation/website/assets/img` Would you mind copying it there as well?

**Comment by stanlemon** [comment]
I put the files in the right place and ran the build command. I couldn't figure out what theme was used previously, but with these images I went ahead and selected 'VSCode' as that seemed reasonable. :)

Also for reference the updated carbon link is [here](https://carbon.now.sh/?bg=rgba(171%252C%2520184%252C%2520195%252C%25201)&t=vscode&wt=none&l=javascript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=48px&ph=32px&ln=false&fm=Hack&fs=14px&lh=133%2525&si=false&es=2x&wm=false&code=const%2520%257B%2520task%252C%2520option%252C%2520logger%252C%2520argv%252C%2520parallel%2520%257D%2520%253D%2520require(%27just-task%27)%253B%250A%250Aoption(%27name%27%252C%2520%257B%2520default%253A%2520%27world%27%257D)%253B%250A%250Atask(%27say-hello%27%252C%2520function()%2520%257B%250A%2520%2520logger.info(%27hello%2520%27%2520%252B%2520argv().name)%253B%250A%257D)%253B%250A%250Atask(%27say-hi%27%252C%2520function()%2520%257B%250A%2520%2520logger.info(%27hi%2520%27%2520%252B%2520argv().name)%253B%250A%257D)%253B%250A%250Atask(%27say-it-all%27%252C%2520parallel(%27say-hello%27%252C%2520%27say-hi%27))%253B).

**Pull request merged**
