### PR TITLE
fix(just-stack): jest config in single-lib stack

### LINKED ISSUE #142: just-stack-single-lib: no jest configuration found, skipping jest
It looks like `just-stack-single-lib` is not creating a jest config.

After scaffolding a new project, then running `npm t`, I get:

```
❯ npm t

> just-single@0.0.1 test .../just-single
> npx just test

[10:35:23 AM] ■ started 'test'
[10:35:23 AM] ■ started 'clean'
[10:35:23 AM] ■ Removing [lib, temp, dist, coverage, lib-commonjs]
[10:35:23 AM] ■ finished 'clean' in 0.01s
[10:35:23 AM] ■ started 'jest'
[10:35:23 AM] ▲ no jest configuration found, skipping jest
[10:35:23 AM] ■ finished 'jest' in 0s
[10:35:23 AM] ■ finished 'test' in 0.04s
```

### PR DESCRIPTION
**Pull request by anikethsaha**
fixes #142 

**Type**
bugfix

**Summary**
added the jest config to package.json , it the jest config file was not copying!

### CODE REVIEW

**Comment by kenotron** [comment]
Can spot in my code where it is copying files that it skips over jest.config.js?

**Comment by anikethsaha** [comment]
https://github.com/microsoft/just/blob/75e150c91b84e31ee1d88e04a7b9e22c1e8b53f7/packages/just-scripts-utils/src/applyTemplate.ts#L29
as per the code, **I think** it should not be missed out!
One more thing we can do is making it `.hbs`

**Comment by anikethsaha** [comment]
@kenotron can you review this!

**Comment by anikethsaha** [comment]
@kenotron ping !

**Pull request closed without merging**
