### PR TITLE
feat(chore): validate user input 

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Warn the user if no input was provided for the `repo-name` prompt.

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
Screenshot from 2019-06-18 15-09-36

**Comment by jamesgeorge007** [comment]
cc @kenotron

**Comment by kenotron** [comment]
Good catch, sorry I don't use semantic release, I use something else - please use "yarn change" to create a change file instead here. I'll write up a contrib guide for ya soon!

**Comment by kenotron** [comment]
Actually this looks good to me actually!

**Comment by jamesgeorge007** [comment]
Any specific reason for keeping this on hold :thinking:

**Comment by kenotron** [comment]
> Any specific reason for keeping this on hold 🤔

No reason - just time! I'm gonna merge this in very soon here.

**Pull request merged**
