### PR TITLE
New task: ESLint

### PR DESCRIPTION
**Pull request by Thisen**
Addressing #122.

Adds a task for running ESLint with a minimal API.

### CODE REVIEW

**Comment by kenotron** [comment]
Thanks so much! I would like to test this out before merging it in today :)

**Comment by kenotron** [comment]
close and reopening to trigger new build

**Comment by kenotron** [comment]
Shoot, the build is suppose to fail without a "change file" - would you terribly mind running this in your repo at the root: "yarn change" - it should walk you through a CLI wizard in creating a "change file" - these change file determine the published version. Given it a description and pick "minor" in this case. I need to update `beachball` to fail the build if it doesn't find it.

**Comment by Thisen** [comment]
@kenotron,`yarn change` results in this output: "No change files are needed"

**Pull request merged**
