### PR TITLE
chore(init): refactored the after done instruction of init command

### PR DESCRIPTION
**Pull request by anikethsaha**
**PR Type**
Refactoring

**Any breaking changes**
NA

**added tests ?**
NA

**Summary**
after the init command ,  the instruction coming from the readme.md.hbs had a missing step to move to the project directory so added `$ cd {{name}}`

### CODE REVIEW

**Comment by kenotron** [comment]
this will require you to do `yarn change` to create a change file.

**Comment by anikethsaha** [comment]
hey, I got the change folder. Do I need to push that now?

I never created changelog with respect to changing of files so its kind of new to me.

**Comment by anikethsaha** [comment]
@kenotron I am not able to commit the change files,  kind of messed up while rebasing.

**Comment by anikethsaha** [comment]
@kenotron ping !!!!!

**Pull request closed without merging**
